---
# tasks file for roles/nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes